---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:alpine
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: password
          volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: "0.50"
              memory: "256Mi"
            requests:
              cpu: "0.25"        
              memory: "128Mi"
      volumes:
      - name: postgres-storage
        emptyDir: {}

---
apiVersion: v1
kind: ClusterIP
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

