apiVersion: v1
kind: Service
metadata:
  name: prod
spec:
  selector:
    app: promotions
  type: NodePort
  internalTrafficPolicy: Local
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 31002
      targetPort: 8080